const { updateTopic } = require('./update_topic.cjs');

const topics = [
  {
    key: 'welcome',
    content: `# Welcome to Kontxt\n\n🕒 **Estimated Time:** 5 min\n\n---\n\n## Why this matters\nBefore you write a single line of code, you must align on your philosophy. The way you build changes drastically depending on your end goal. Kontxt dynamically adjusts its playbook based on the mode you select.\n\n## Strategic Guidance\n\n### Hackathon Mode\nIn Hackathon Mode, speed is everything. Your only goal is to build a visually impressive demo before the clock runs out. \n\nYou will ignore scalable architecture, skip rigorous testing, and fake backend data if necessary. Technical debt is not a concern; the only thing that matters is the final presentation to the judges. Stay ruthless with your scope.\n\n### Personal Project\nIn Personal Project mode, your goal is learning and zero-cost maintenance. \n\nYou are building this to scratch an itch or bolster your resume. You should optimize for using free tiers (Vercel, Supabase, Render) and experimenting with new, exciting tech stacks that you want to master. Don't over-engineer it for scale you don't have.\n\n### Production SaaS\nIn Production SaaS mode, you are building a real business that will accept credit cards. \n\nThis means you cannot cut corners on security, authentication, or basic architecture. You must build a robust foundation that won't collapse when you get your first 100 paying customers. You need proper testing, staging environments, and database migrations.\n\n### Custom Mode\nCustom Mode is for enterprise-grade, massive scale applications. \n\nBefore you write code, you must pass rigorous compliance checks (SOC2, HIPAA). You need to define your buying committee, design highly resilient microservices (or modular monoliths), and plan for strict Service Level Agreements (SLAs). Every decision must be vetted.\n\n## Accountability Check\n- [ ] I understand the philosophy of my chosen mode and I am ready to begin.\n`
  },
  {
    key: 'problemstatement',
    content: `# Problem Statement\n\n🕒 **Estimated Time:** 20 min\n\n---\n\n## Why this matters\nIf you don't clearly define the problem, you will build a solution looking for a use case. The best software eliminates a specific, acute pain point.\n\n## Strategic Guidance\n\n### Hackathon Mode\nHackathons are often themed (e.g., "AI for Good", "Future of Finance"). Your problem statement should directly align with the hackathon's core theme to maximize your chances of winning.\n\nDon't worry if the problem is slightly contrived; as long as the judges resonate with it emotionally, it serves its purpose for the pitch.\n\n### Personal Project\nFor a personal project, the best problem statement is one you personally experience every day.\n\n"I hate having to manually format my resume every time I apply for a job." This is a fantastic problem statement because you are the user. You don't need market research to validate it.\n\n### Production SaaS\nIn a Production SaaS, the problem must be monetizable. It must be a "Hair on Fire" problem.\n\nIf the user's hair is on fire, and you offer them a brick, they will buy it to put the fire out. That is how painful the problem needs to be. If the problem is just "it would be nice if this was 10% faster," it will be incredibly difficult to get people to pay for it.\n\n### Custom Mode\nIn enterprise, the problem statement must be tied directly to a massive financial metric: either it makes the company millions of dollars, or it saves the company millions of dollars.\n\nFurthermore, the problem must be felt by someone with budget authority. If you solve a problem for junior developers, but the CTO doesn't care about it, you will never pass procurement.\n\n## Define the Problem\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  },
  {
    key: 'userpainpoints',
    content: `# User Pain Points\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nPain points are the granular symptoms of your Problem Statement. Identifying the exact friction points allows you to design features that directly neutralize them.\n\n## Strategic Guidance\n\n### Hackathon Mode\nFocus on visual pain points. What current process looks the ugliest or takes the most manual clicks? \n\nIf you can show a "Before" video of a user struggling with 10 clunky steps, and an "After" video of your app doing it in 1 click, the judges will love it.\n\n### Personal Project\nMap out your exact workflow. Where do you sigh in frustration? Where do you resort to using a messy Excel sheet? Those are your pain points.\n\n### Production SaaS\nRank pain points by how much money or time they waste. \n\nWhen you talk to users, listen for emotional words: "I hate", "It's so annoying", "I lose hours doing this." If a pain point doesn't evoke a strong emotional response, it's not painful enough to build a SaaS around.\n\n### Custom Mode\nEnterprise pain points usually revolve around compliance, siloed data, and lack of visibility. \n\nThe VP of Sales doesn't care that the UI requires 3 clicks instead of 2. They care that the CRM data isn't syncing with the ERP, causing a 5% loss in revenue attribution. Focus on systemic, organizational pain points.\n\n## The Pain Points\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  },
  {
    key: 'targetusers',
    content: `# Target Users\n\n🕒 **Estimated Time:** 10 min\n\n---\n\n## Why this matters\n"Everyone" is not a target audience. If you build for everyone, you build for no one. You need a highly specific niche to gain initial traction.\n\n## Strategic Guidance\n\n### Hackathon Mode\nYour target user is the judging panel. \n\nIf the judges are mostly engineers, build a dev-tool. If the judges are business executives, build a dashboard. Tailor the entire experience to the people grading you.\n\n### Personal Project\nYour target user is you, and perhaps a small community you are a part of (e.g., a specific Discord server or a niche subreddit).\n\n### Production SaaS\nYour target users must be "desperate" and "reachable." \n\nIf your target users are "Small Business Owners," that is too broad. How do you reach them? Instead, target "Independent Dental Practices in the US who struggle with scheduling." Now you know exactly who to cold-email and what their specific needs are.\n\n### Custom Mode\nYour target users are massive corporations in highly regulated industries (Finance, Healthcare, Government). \n\nThese users have extremely high expectations for security, audit logs, and uptime. You are not selling to a person; you are selling to a procurement department.\n\n## Your Specific Audience\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  },
  {
    key: 'icpidealcustomerprofile',
    content: `# Ideal Customer Profile (ICP)\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nWhile a Target User is a *person*, an ICP is the *company* or *entity* that employs them. Knowing your ICP tells you who has the budget to pay for your product.\n\n## Strategic Guidance\n\n### Hackathon Mode\nSkip this entirely. You don't need a corporate ICP for a weekend project.\n\n### Personal Project\nSkip this. You are building for individuals, not B2B companies.\n\n### Production SaaS\nYou must define the company size, revenue, and industry. \n\nFor example: "B2B SaaS companies with 50-200 employees, doing $5M-$20M in ARR, struggling with churn." If a company with 5 employees tries to buy your product, they are NOT your ICP, and you should not build custom features for them, even if they complain.\n\n### Custom Mode\nYour ICP is the Fortune 500. \n\nYou must define the exact technographic profile of the company. Do they use Salesforce? Do they use AWS or Azure? You need to know exactly what existing infrastructure they have so you can build enterprise integrations that fit seamlessly into their stack.\n\n## Define the ICP\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  },
  {
    key: 'solutionstatement',
    content: `# Solution Statement\n\n🕒 **Estimated Time:** 10 min\n\n---\n\n## Why this matters\nThis is the core mechanic of your product. How exactly does your software eliminate the pain point?\n\n## Strategic Guidance\n\n### Hackathon Mode\nYour solution must sound like magic. "We use AI to instantly..." or "A real-time Web3 protocol that..." \n\nThe technical "how" is less important than the impressiveness of the "what."\n\n### Personal Project\nThe solution should be an elegant, lightweight script or app that automates the boring part of your workflow.\n\n### Production SaaS\nThe solution must be a scalable software product that integrates into the user's existing habits. \n\nDon't force users to change their behavior. If they live in Slack, your solution should be a Slack bot. If they live in their inbox, your solution should integrate with Gmail.\n\n### Custom Mode\nThe solution must be an extensible platform. \n\nEnterprises don't buy point solutions; they buy platforms that can replace 3 other tools. Your solution must include robust APIs, webhooks, and single sign-on (SSO) to integrate with their massive IT ecosystems.\n\n## Describe the Solution\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  },
  {
    key: 'valueproposition',
    content: `# Value Proposition\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nA value proposition is a concise promise of value to be delivered. It is the #1 reason a prospect should buy from you instead of your competitors. It's the headline of your landing page.\n\n## Strategic Guidance\n\n### Hackathon Mode\nYour value proposition is the hook for your presentation. \n\n"We built Tinder for X" or "We make X 100x faster using LLMs." It needs to be catchy, memorable, and instantly understood by a tired judge at 2 AM.\n\n### Personal Project\nYour value proposition is simply the time or mental energy you are saving yourself.\n\n### Production SaaS\nYour value proposition must focus on outcomes, not features. \n\nBad: "We have an AI-powered dashboard with real-time analytics."\nGood: "Cut your customer churn in half without hiring more support agents."\nPeople don't buy dashboards; they buy lower churn.\n\n### Custom Mode\nYour value proposition must align with boardroom-level strategic initiatives. \n\n"Ensure global GDPR compliance and prevent multi-million dollar data breaches." You are selling risk mitigation and massive operational efficiency at a global scale.\n\n## The Core Value Prop\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  },
  {
    key: 'elevatorpitch',
    content: `# Elevator Pitch\n\n🕒 **Estimated Time:** 10 min\n\n---\n\n## Why this matters\nYou have 30 seconds to explain what you do before the person stops listening. The elevator pitch is your standard answer to "So, what are you working on?"\n\n## Strategic Guidance\n\n### Hackathon Mode\nYour pitch must be high-energy and focus on the impressive technology you managed to stitch together in 48 hours.\n\n### Personal Project\nKeep it casual. "I got annoyed by X, so I built a little app that does Y."\n\n### Production SaaS\nUse the standard format: "For [Target User] who [Problem], our product is a [Category] that provides [Value Proposition]. Unlike [Competitor], we [Key Differentiator]."\n\nPractice this until you can say it smoothly without sounding like a robot.\n\n### Custom Mode\nYour pitch must immediately establish authority and scale. "We provide the infrastructure for Fortune 500 companies to securely manage X." Drop names if you have them.\n\n## Your Pitch\n\`\`\`input\nWrite Here...\n\`\`\`\n`
  }
];

let allSuccess = true;
for (const u of topics) {
  if (!updateTopic(u.key, u.content)) {
    allSuccess = false;
  }
}

if (allSuccess) {
  console.log("Batch 1 Deep Content applied!");
} else {
  console.error("Errors occurred in Batch 1.");
  process.exit(1);
}
