const { updateTopic } = require('./update_topic.cjs');

const topics = [
  {
    key: 'informationarchitecture',
    content: `# Information Architecture\n\n🕒 **Estimated Time:** 20 min\n\n---\n\n## Why this matters\nInformation Architecture (IA) is the skeleton of your app. It dictates how pages are organized and how users navigate between them. If your IA is confusing, users will get lost and abandon your app.\n\n## Strategic Guidance\n\n### Hackathon Mode\nKeep it flat. You don't have time to build nested navigation or complex routing. Your entire app should ideally be a single dashboard or a 3-step linear flow (Home -> Action -> Result).\n\n### Personal Project\nMap out a simple sitemap. A Top Nav for global pages, and a Sidebar for nested settings, is usually sufficient. Stick to standard, recognizable patterns.\n\n### Production SaaS\nYour IA must support future scalability. \n\nIf you add 10 new features next year, where will they live in the navigation? You need a robust hierarchy. Differentiate between global navigation (Billing, Settings, Profile) and workspace navigation (Dashboards, Projects, Reports). Use breadcrumbs to keep users oriented.\n\n### Custom Mode\nIn enterprise software, IA is heavily dependent on Role-Based Access Control (RBAC). \n\nAn Admin sees a completely different sitemap than a standard Employee. Your IA documentation must map out the navigation tree *per user role*, ensuring that restricted pages are completely hidden from unauthorized users' navigation menus.\n\n## IA Generation\n\`\`\`prompt\nAct as a UX Architect. Based on my PRD, generate a comprehensive sitemap and Information Architecture hierarchy.\n\`\`\`\n- [ ] I have mapped out my app's navigation structure.\n`
  },
  {
    key: 'wireframes',
    content: `# Wireframes\n\n🕒 **Estimated Time:** 45 min\n\n---\n\n## Why this matters\nWireframes are low-fidelity blueprints. They allow you to rapidly iterate on layout and hierarchy without getting bogged down by colors, fonts, or padding. Moving a box in a wireframe takes 2 seconds; rewriting a React component takes 2 hours.\n\n## Strategic Guidance\n\n### Hackathon Mode\nSkip traditional wireframes. You don't have time. Draw the 3 main screens on a piece of paper or a whiteboard in 5 minutes, agree on the layout with your team, and start coding immediately.\n\n### Personal Project\nUse a tool like Excalidraw or Balsamiq to quickly map out the core screens. Keep it low-fidelity (black and white). Do not spend time perfecting alignment.\n\n### Production SaaS\nWireframes are a critical step before handing off to high-fidelity UI design. \n\nYou must wireframe every major flow, including empty states (what the app looks like before they add data) and error states. Use Figma. Validate these wireframes with potential users to ensure the layout makes logical sense before investing in high-fidelity design.\n\n### Custom Mode\nWireframes must be annotated with specific technical and business logic requirements. \n\nFor example, if a table is wireframed, the annotation must specify if the table requires server-side pagination, sorting, or complex filtering. The wireframe acts as a visual contract for the engineering team.\n\n## Wireframe Generation\n\`\`\`prompt\nAct as a UX Designer. Describe the layout, components, and visual hierarchy for the 3 main screens of my app.\n\`\`\`\n- [ ] I have generated wireframes for my core screens.\n`
  },
  {
    key: 'branding',
    content: `# Branding\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nBranding is how your product makes the user *feel*. It encompasses your logo, color palette, tone of voice, and overall aesthetic. Good branding builds trust.\n\n## Strategic Guidance\n\n### Hackathon Mode\nYour brand is your project name and a single primary color. Go to a free logo generator, pick a modern-looking icon, and move on. Do not spend more than 5 minutes on this.\n\n### Personal Project\nPick a name you like and a color palette that feels right to you. You can use tools like Coolors or Tailwind's default palette to find something aesthetically pleasing quickly.\n\n### Production SaaS\nYour branding must evoke trust and professionalism, tailored specifically to your [ICP](#icpidealcustomerprofile). \n\nIf you are selling to banks, use conservative blues and a serious tone. If you are selling to Gen-Z creators, use vibrant gradients and a casual tone. Your branding must be perfectly consistent across your landing page, your app UI, and your transactional emails.\n\n### Custom Mode\nEnterprise branding requires a comprehensive Brand Guidelines document. \n\nThis dictates exactly how the logo can be used, the minimum clear space around it, the exact Pantone colors for print vs digital, and the strict tone of voice for all external communications. It ensures that 50 different employees all represent the company identically.\n\n## Brand Identity\n\`\`\`prompt\nAct as a Brand Strategist. Suggest 3 brand names, a color palette, and a tone of voice for my product.\n\`\`\`\n- [ ] I have chosen a name and brand identity.\n`
  },
  {
    key: 'accessibility',
    content: `# Accessibility (a11y)\n\n🕒 **Estimated Time:** 10 min\n\n---\n\n## Why this matters\nAccessibility ensures your software can be used by people with disabilities (visual, auditory, motor, or cognitive). Building inaccessible software is not only unethical, it also drastically shrinks your addressable market.\n\n## Strategic Guidance\n\n### Hackathon Mode\nIgnore it. In a 48-hour sprint where you are just trying to get a demo working for able-bodied judges, accessibility is a luxury you cannot afford. Use ` + '\\`' + `div` + '\\`' + ` tags for buttons if you have to.\n\n### Personal Project\nTry to use semantic HTML (use ` + '\\`' + `<button>` + '\\`' + ` instead of ` + '\\`' + `<div onClick={}>` + '\\`' + `). It's a good habit to build and takes zero extra time, but don't obsess over perfect ARIA labels.\n\n### Production SaaS\nYou must hit baseline accessibility standards. \n\nYour brand colors must pass the WCAG AA contrast ratio (text must be readable against the background). Your core workflows must be navigable via keyboard (Tab and Enter). If a user relies on a screen reader, they should be able to sign up and pay you.\n\n### Custom Mode\nAccessibility is a strict legal requirement. \n\nEnterprise and Government contracts explicitly require full WCAG 2.1 AA (and sometimes AAA) compliance. You must build extensive ARIA attributes, support high-contrast modes, provide transcripts for media, and undergo regular third-party accessibility audits. If you fail an audit, you lose the contract.\n\n## Accountability Check\n- [ ] I understand the accessibility requirements for my project mode.\n`
  }
];

let allSuccess = true;
for (const u of topics) {
  if (!updateTopic(u.key, u.content)) {
    allSuccess = false;
  }
}

if (allSuccess) {
  console.log("Batch 3b Deep Content applied!");
} else {
  console.error("Errors occurred in Batch 3b.");
  process.exit(1);
}
