const { updateTopic } = require('./update_topic.cjs');

const topics = [
  {
    key: 'auth',
    content: `# Authentication Setup\n\n🕒 **Estimated Time:** 45 min\n\n---\n\n## Why this matters\nAuthentication is usually the very first code you write. Without it, you have no users. Getting it wrong leads to security vulnerabilities.\n\n## Strategic Guidance\n\n### Hackathon Mode\nIf you don't actually need user-specific data, skip Auth entirely. \n\nIf you do, use Clerk or Supabase Auth. Do not waste time building custom UI for the login screen. Use the pre-built, drop-in React components (like ` + '\\`' + `<SignIn />` + '\\`' + `) that take 5 minutes to install.\n\n### Personal Project\nUse Supabase Auth. It is free, robust, and connects directly to your Postgres database. Build your own custom login UI if you want to practice form handling and state management.\n\n### Production SaaS\nUse a managed Auth provider (Supabase Auth, Auth0, Clerk). \n\nYou must configure strict Redirect URLs to prevent Open Redirect vulnerabilities. You must implement robust error handling (e.g., "Email already in use"). You should strongly consider implementing Social Login (Google, GitHub) to drastically increase your signup conversion rate.\n\n### Custom Mode\nEnterprise Auth requires SSO/SAML integration. \n\nYou must integrate with an enterprise identity provider like Okta or Microsoft Entra ID. Your auth flow must support Just-In-Time (JIT) provisioning so when an employee clicks the app in their Okta dashboard, an account is automatically created for them without requiring a signup form.\n\n## Auth Prompt\n\`\`\`prompt\nAct as a Security Engineer. Generate the frontend code and backend configuration to integrate Supabase Authentication into my React app.\n\`\`\`\n- [ ] I have successfully implemented Authentication.\n`
  },
  {
    key: 'database',
    content: `# Database Setup\n\n🕒 **Estimated Time:** 60 min\n\n---\n\n## Why this matters\nYour database is the heart of your application. You must initialize your schema, set up migrations, and write your first queries.\n\n## Strategic Guidance\n\n### Hackathon Mode\nUse the Supabase SQL Editor and execute your schema creation script directly in the browser. \n\nDo not bother setting up local development databases, Docker containers, or migration files. You don't have time. Just spin up the cloud database and start querying it.\n\n### Personal Project\nSet up a local PostgreSQL instance (using Docker or Postgres.app). Write your schema in an ` + '\\`' + `init.sql` + '\\`' + ` file. Practice writing raw SQL queries before you abstract them away with an ORM.\n\n### Production SaaS\nYou must use an ORM (like Prisma, Drizzle, or Supabase clients) and implement database migrations. \n\nNever change your production database schema directly in a UI. You must create migration files (e.g., ` + '\\`' + `001_create_users_table.sql` + '\\`' + `) and commit them to version control. This ensures your staging database and production database are always perfectly in sync.\n\n### Custom Mode\nEnterprise databases require strict Row Level Security (RLS) and Audit Logging. \n\nEvery single table must have policies dictating exactly which roles can read, insert, update, or delete rows. You must configure connection pooling (PgBouncer) to ensure the database doesn't crash when 5,000 employees log in at 9:00 AM.\n\n## Database Prompt\n\`\`\`prompt\nAct as a Database Administrator. Generate the SQL migration file to create my initial database schema, including Row Level Security (RLS) policies.\n\`\`\`\n- [ ] I have set up my database and migrations.\n`
  },
  {
    key: 'backend',
    content: `# Backend Development\n\n🕒 **Estimated Time:** 2-4 Hours\n\n---\n\n## Why this matters\nThe backend handles your business logic, talks to the database, and secures your data. This is where the heavy lifting happens.\n\n## Strategic Guidance\n\n### Hackathon Mode\nIf you are using Supabase, you can often skip writing a custom backend entirely by querying the database directly from the frontend (using Row Level Security for safety). \n\nIf you need custom logic (like calling the OpenAI API), write a simple Serverless Edge Function. Keep it as lightweight as possible.\n\n### Personal Project\nBuild a standard Node.js/Express server or use Next.js API routes. Focus on learning how to handle requests, parse JSON bodies, and return proper HTTP status codes.\n\n### Production SaaS\nYou must implement robust error handling, input validation (using Zod or Joi), and rate limiting. \n\nNever trust data coming from the frontend. Always re-validate inputs on the backend. Structure your backend into logical layers: Routes (handling HTTP), Controllers (business logic), and Services/Repositories (database interactions). This keeps your code testable and clean.\n\n### Custom Mode\nEnterprise backends must be observable. \n\nYou must implement structured logging (JSON logs), distributed tracing (OpenTelemetry), and health check endpoints. Your APIs must be versioned (` + '\\`' + `/api/v1/` + '\\`' + `) so you don't break existing enterprise clients when you update the code.\n\n## Backend Prompt\n\`\`\`prompt\nAct as a Backend Engineer. Write the server-side code to handle my core application logic, including input validation and error handling.\n\`\`\`\n- [ ] I have implemented my core backend logic.\n`
  },
  {
    key: 'frontend',
    content: `# Frontend Development\n\n🕒 **Estimated Time:** 3-5 Hours\n\n---\n\n## Why this matters\nThe frontend is what your users actually touch. If it is laggy, ugly, or confusing, they will assume the entire product is broken.\n\n## Strategic Guidance\n\n### Hackathon Mode\nUse pre-built component libraries (shadcn/ui, Tailwind UI, MUI). \n\nDo not spend 20 minutes writing custom CSS for a button hover effect. Copy-paste components. Focus all your energy on the single core user flow that you will demonstrate during the pitch.\n\n### Personal Project\nBuild components from scratch to understand how React state, props, and hooks work. Focus on clean, readable code rather than rushing to the finish line.\n\n### Production SaaS\nYou must implement optimistic UI updates, loading skeletons, and robust error boundaries. \n\nWhen a user clicks "Save", the button should instantly show a loading spinner, and the UI should optimistically update before the server responds. If the server throws an error, gracefully revert the UI and show a toast notification. Never let the app crash to a white screen.\n\n### Custom Mode\nEnterprise frontends require massive data tables and complex forms. \n\nYou must implement server-side pagination, virtualization for rendering thousands of rows (e.g., TanStack Virtual), and highly complex form validation schemas. You must ensure the UI is fully accessible (WCAG 2.1 AA) and supports internationalization (i18n) if the enterprise has global offices.\n\n## Frontend Prompt\n\`\`\`prompt\nAct as a Senior Frontend Developer. Write the React components for my main dashboard, utilizing Tailwind CSS and optimistic UI updates.\n\`\`\`\n- [ ] I have built my core frontend views.\n`
  },
  {
    key: 'payments',
    content: `# Payments Integration\n\n🕒 **Estimated Time:** 2 Hours\n\n---\n\n## Why this matters\nIf you can't collect money, you don't have a business. Payment integration is notoriously tricky because you are dealing with real money and webhooks.\n\n## Strategic Guidance\n\n### Hackathon Mode\nDo not integrate real payments. \n\nIf you want to show a checkout flow for the demo, just build a fake UI screen that says "Payment Successful." The judges do not care if your Stripe integration actually works.\n\n### Personal Project\nIntegrate Stripe Checkout in "Test Mode." It's a fantastic learning experience to understand how webhooks confirm payment status.\n\n### Production SaaS\nUse Stripe Checkout or Lemon Squeezy (if you need a Merchant of Record to handle global taxes). \n\nYou must rely on Webhooks to provision access, not client-side redirects. When a user pays, Stripe sends a webhook to your server; your server verifies the webhook signature, updates the user's ` + '\\`' + `subscription_status` + '\\`' + ` in the database, and only *then* does the user get access.\n\n### Custom Mode\nEnterprise payments are rarely self-serve via credit card. \n\nYou will need to support custom invoicing (Net-30, Net-60 terms), ACH transfers, and Wire Transfers. You will use Stripe Billing to generate invoices, but the actual payment might happen via a bank transfer 45 days later. Your system must handle "Pending" and "Overdue" account states gracefully.\n\n## Payments Prompt\n\`\`\`prompt\nAct as a Stripe Integration Expert. Write the backend webhook handler to process subscription lifecycle events (created, updated, canceled).\n\`\`\`\n- [ ] I have integrated my payment gateway.\n`
  },
  {
    key: 'emails',
    content: `# Transactional Emails\n\n🕒 **Estimated Time:** 1 Hour\n\n---\n\n## Why this matters\nUsers need to receive Welcome emails, Password Resets, and Receipts. If these emails go to spam, your users will get locked out or confused.\n\n## Strategic Guidance\n\n### Hackathon Mode\nSkip transactional emails. \n\nIf you need to show an email feature during the demo, just ` + '\\`' + `console.log` + '\\`' + ` the email content to the terminal or show a fake "Email Sent!" toast notification.\n\n### Personal Project\nUse Resend or SendGrid. They have great developer APIs and free tiers. It's a great skill to learn.\n\n### Production SaaS\nYou must use a dedicated transactional email provider (Resend, Postmark). \n\nYou must configure your domain's DKIM, SPF, and DMARC records to ensure your emails actually land in the Inbox, not the Spam folder. Use a tool like React Email to build beautiful, responsive HTML templates instead of writing raw HTML strings.\n\n### Custom Mode\nEnterprise emails often require strict compliance. \n\nYou must ensure that PII (Personally Identifiable Information) is never transmitted in plain text via email. You must provide a highly granular "Notification Preferences" center so enterprise users can opt-out of specific email categories to comply with strict internal corporate policies.\n\n## Email Prompt\n\`\`\`prompt\nAct as a Communications Architect. Generate a React Email template for my Welcome Email, including my branding colors and a clear Call to Action.\n\`\`\`\n- [ ] I have configured my transactional emails.\n`
  }
];

let allSuccess = true;
for (const u of topics) {
  if (!updateTopic(u.key, u.content)) {
    allSuccess = false;
  }
}

if (allSuccess) {
  console.log("Batch 5a Deep Content applied!");
} else {
  console.error("Errors occurred in Batch 5a.");
  process.exit(1);
}
