const { updateTopic } = require('./update_topic.cjs');

const topics = [
  {
    key: 'authentication',
    content: `# Authentication\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nAuthentication verifies *who* the user is. If you mess this up, you leak user data and ruin your reputation instantly.\n\n## Strategic Guidance\n\n### Hackathon Mode\nFake it. \n\nHardcode a single user session into your app's state. Don't waste 4 hours trying to get OAuth working when you could be building the core feature. If you absolutely must have auth, use Supabase Auth or Clerk and stick strictly to Email/Password.\n\n### Personal Project\nUse this as an opportunity to learn how JWTs (JSON Web Tokens) or session cookies actually work under the hood. Build your own simple auth flow just for the learning experience.\n\n### Production SaaS\nDo not build your own auth. \n\nUse an established provider like Supabase Auth, Auth0, or Clerk. You must support social logins (Google, GitHub) to reduce onboarding friction. You must implement password resets and email verification perfectly.\n\n### Custom Mode\nEnterprise authentication is entirely about SAML and SSO. \n\nEnterprise users do not want to create a new password for your app. They want to log in using their Okta or Microsoft Entra ID. If you do not support SAML/SSO, you cannot sell to the Fortune 500. Period.\n\n## Accountability Check\n- [ ] I understand my authentication strategy.\n`
  },
  {
    key: 'authorizationroles',
    content: `# Authorization & Roles\n\n🕒 **Estimated Time:** 20 min\n\n---\n\n## Why this matters\nWhile Authentication is *who* you are, Authorization is *what you are allowed to do*. Without strict authorization, any user can delete any other user's data.\n\n## Strategic Guidance\n\n### Hackathon Mode\nIgnore it. Assume the single user you are demoing has admin access to everything.\n\n### Personal Project\nHardcode a simple ` + '\\`' + `isAdmin` + '\\`' + ` boolean on your user table. That is usually enough for a small app.\n\n### Production SaaS\nYou must implement a robust authorization system. \n\nIf using Supabase, use Row Level Security (RLS) to ensure users can only query rows that belong to their tenant/workspace ID. Do not rely solely on frontend authorization (hiding buttons); the backend API must explicitly reject unauthorized requests.\n\n### Custom Mode\nEnterprise requires extremely granular Role-Based Access Control (RBAC). \n\nYou cannot just have "Admin" and "User." You need custom roles where a client can specify that "Role A can view Reports, edit Users, but cannot delete Projects." You must build a UI that allows Enterprise IT admins to configure these custom roles themselves.\n\n## Authorization Generation\n\`\`\`prompt\nAct as a Security Architect. Based on my PRD, define the standard user roles and their specific permissions.\n\`\`\`\n- [ ] I have defined my user roles and permissions.\n`
  },
  {
    key: 'databaseschema',
    content: `# Database Schema\n\n🕒 **Estimated Time:** 30 min\n\n---\n\n## Why this matters\nThe database schema is the foundation of your backend. A bad schema requires complex, slow SQL queries to extract simple data, and migrating a bad schema in production is terrifying.\n\n## Strategic Guidance\n\n### Hackathon Mode\nUse a schema-less NoSQL database (like Firebase Firestore) or just throw everything into a single massive Postgres table. \n\nData normalization does not matter. If you have duplicate data, who cares? The database will be deleted on Monday.\n\n### Personal Project\nDesign a clean, normalized relational schema. Practice drawing Entity-Relationship (ER) diagrams and writing clean foreign key relationships.\n\n### Production SaaS\nUse a mature relational database like PostgreSQL. \n\nYour schema must be multi-tenant from Day 1. Almost every table should have a ` + '\\`' + `workspace_id` + '\\`' + ` or ` + '\\`' + `tenant_id` + '\\`' + ` column. You must plan for indexing on columns you will query frequently. Never use hard deletes; use soft deletes (` + '\\`' + `deleted_at` + '\\`' + ` timestamps) so you can recover data if a user accidentally clicks delete.\n\n### Custom Mode\nEnterprise schemas must be designed for extreme scale and auditability. \n\nYou might need to physically separate tenant data into different databases or schemas (Database-per-tenant) to satisfy strict data isolation compliance laws. Every single mutation must be logged in an immutable audit trail table.\n\n## Schema Generation\n\`\`\`prompt\nAct as a Database Administrator. Based on my PRD, generate a PostgreSQL schema including multi-tenant architecture and foreign keys.\n\`\`\`\n- [ ] I have finalized my database schema.\n`
  },
  {
    key: 'filestorage',
    content: `# File Storage\n\n🕒 **Estimated Time:** 10 min\n\n---\n\n## Why this matters\nIf your users upload images, PDFs, or videos, you cannot store them in your database. You need a dedicated object storage solution.\n\n## Strategic Guidance\n\n### Hackathon Mode\nDon't support file uploads if you can avoid it. If you must, just upload files directly to the public folder of your host or use a free Supabase Storage bucket with public access. Don't worry about resizing or security.\n\n### Personal Project\nUse Supabase Storage or AWS S3. It's a great opportunity to learn how to handle multipart form data and signed URLs.\n\n### Production SaaS\nYou must use secure Object Storage (AWS S3, Cloudflare R2). \n\nFiles should never be completely public unless they are avatars. Generate short-lived Signed URLs for users to download their files. You must implement file size limits and scan uploads for malware to prevent malicious actors from abusing your storage.\n\n### Custom Mode\nEnterprise storage requires compliance and redundancy. \n\nYou must guarantee that data is replicated across multiple geographic regions (Multi-Region S3). You must support Data Loss Prevention (DLP) to ensure employees aren't uploading files containing Social Security Numbers.\n\n## Accountability Check\n- [ ] I understand my file storage strategy.\n`
  },
  {
    key: 'thirdpartyintegrations',
    content: `# Third Party Integrations\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nModern software doesn't live in a vacuum. Integrating with tools your users already use (Slack, Salesforce, Stripe) increases your product's stickiness.\n\n## Strategic Guidance\n\n### Hackathon Mode\nIntegrations are the easiest way to add "wow factor." \n\nIntegrating a Twilio SMS or a Stripe checkout looks incredibly impressive and only takes 10 lines of code. Use them aggressively to make your app look more feature-rich than it actually is.\n\n### Personal Project\nIntegrate with 1 or 2 APIs just to learn how to handle Webhooks and OAuth flows.\n\n### Production SaaS\nOnly build integrations that directly drive revenue or retention. \n\nA Stripe integration is mandatory. A Slack integration is highly recommended for B2B. Don't build a massive integrations catalog on Day 1. Wait until users explicitly ask for them.\n\n### Custom Mode\nEnterprise software must integrate with massive legacy systems. \n\nYou will need to support Salesforce, Workday, or SAP. These integrations are notoriously difficult and often require custom professional services work. You might need to use an embedded integration platform (like Merge.dev or Paragon) to handle the complexity.\n\n## Accountability Check\n- [ ] I have identified necessary third-party integrations.\n`
  },
  {
    key: 'aiarchitectureoptional',
    content: `# AI Architecture\n\n🕒 **Estimated Time:** 15 min\n\n---\n\n## Why this matters\nIf you are building an AI product, the way you architect your LLM calls dictates your speed, cost, and output quality.\n\n## Strategic Guidance\n\n### Hackathon Mode\nJust hit the OpenAI API directly from your frontend (but be careful not to leak your key in a public repo). Use the biggest, smartest model available (GPT-4o or Claude 3.5 Sonnet) because cost doesn't matter for a weekend demo.\n\n### Personal Project\nExperiment with open-source models using Ollama, or try using cheaper, faster models like GPT-4o-mini to see how much you can optimize performance.\n\n### Production SaaS\nYou must build a robust AI backend. \n\nNever call LLMs directly from the frontend; proxy them through your backend to protect your API keys and implement rate limiting. You must handle streaming responses (Server-Sent Events) so the user doesn't stare at a loading spinner for 10 seconds. Implement caching (like Redis) for identical queries to save money.\n\n### Custom Mode\nEnterprises will not allow you to send their proprietary data to OpenAI's public endpoints. \n\nYou must use provisioned, private models (like Azure OpenAI) where data is explicitly NOT used for training. You may need to self-host open-source models (Llama 3) entirely within their Virtual Private Cloud (VPC) to meet strict privacy laws.\n\n## Accountability Check\n- [ ] I understand my AI architecture constraints.\n`
  }
];

let allSuccess = true;
for (const u of topics) {
  if (!updateTopic(u.key, u.content)) {
    allSuccess = false;
  }
}

if (allSuccess) {
  console.log("Batch 4b Deep Content applied!");
} else {
  console.error("Errors occurred in Batch 4b.");
  process.exit(1);
}
