const { updateTopic } = require('./update_topic.cjs');

const topics = [
  {
    key: 'notifications',
    content: `# Notifications\n\n🕒 **Estimated Time:** 1 Hour\n\n---\n\n## Why this matters\nNotifications pull users back into your app. Without them, users forget your app exists.\n\n## Strategic Guidance\n\n### Hackathon Mode\nFake it. \n\nShow a static bell icon with a red "1" on it. When clicked, show a hardcoded message. Do not spend time implementing WebSockets or Push Notifications.\n\n### Personal Project\nImplement a simple polling mechanism or basic WebSockets just to learn how real-time data works.\n\n### Production SaaS\nYou must build a robust notification center. \n\nUse a unified API like Novu or Courier. You must support in-app toasts, in-app inbox (the bell icon), and email fallbacks. Crucially, you must allow users to mute specific types of notifications, otherwise they will mark your emails as Spam and destroy your domain reputation.\n\n### Custom Mode\nEnterprise notifications require strict auditability and delivery guarantees. \n\nIf a critical alert is triggered, you must guarantee delivery via SMS, Email, and PagerDuty. You must implement robust retry logic and Dead Letter Queues (DLQs) in case the notification provider goes down.\n\n## Accountability Check\n- [ ] I have implemented my notification strategy.\n`
  },
  {
    key: 'search',
    content: `# Search\n\n🕒 **Estimated Time:** 1-2 Hours\n\n---\n\n## Why this matters\nAs your users generate more data, they will expect to find it instantly. A bad search experience is incredibly frustrating.\n\n## Strategic Guidance\n\n### Hackathon Mode\nJust use a standard SQL \`ILIKE\` query or a simple Array \`.filter()\` on the frontend if the dataset is small. Do not set up a dedicated search engine.\n\n### Personal Project\nImplement basic full-text search directly in Postgres. It's a great feature to learn and requires no extra infrastructure.\n\n### Production SaaS\nFor a production app, Postgres full-text search is usually sufficient until you hit massive scale. \n\nYou must implement "fuzzy matching" so typos don't return zero results. Implement debouncing on your frontend search input (wait 300ms after the user stops typing before hitting the API) to save database compute costs.\n\n### Custom Mode\nAt enterprise scale, Postgres full-text search will buckle. \n\nYou must implement a dedicated search index like Elasticsearch, Algolia, or Meilisearch. Your search results must respect Role-Based Access Control (RBAC)—a user should never see search results for documents they do not have permission to view.\n\n## Accountability Check\n- [ ] I have implemented scalable search.\n`
  },
  {
    key: 'analytics',
    content: `# Product Analytics\n\n🕒 **Estimated Time:** 45 min\n\n---\n\n## Why this matters\nIf you aren't measuring user behavior, you are flying blind. You won't know where users drop off in your funnel or which features they actually use.\n\n## Strategic Guidance\n\n### Hackathon Mode\nSkip it. Analytics will not help you win the pitch.\n\n### Personal Project\nSkip it, unless you specifically want to learn how to implement an analytics SDK.\n\n### Production SaaS\nYou must implement PostHog, Mixpanel, or Amplitude from Day 1. \n\nTrack the "Aha!" moment. Track where users drop off during onboarding. Track feature usage. Connect your frontend SDK to capture pageviews, and send backend events for critical actions (like \`User Upgraded\` or \`Invoice Paid\`) to ensure the data is perfectly accurate.\n\n### Custom Mode\nEnterprises will not allow you to use third-party tracking scripts (like Google Analytics) due to strict privacy laws (GDPR, CCPA). \n\nYou must implement a self-hosted analytics solution, or ensure your vendor is strictly HIPAA/SOC2 compliant and acts only as a Data Processor. You must respect "Do Not Track" headers and provide robust Cookie Consent banners.\n\n## Accountability Check\n- [ ] I have integrated product analytics.\n`
  },
  {
    key: 'adminpanel',
    content: `# Admin Panel\n\n🕒 **Estimated Time:** 2 Hours\n\n---\n\n## Why this matters\nWhen a user inevitably breaks their account, or requests a refund, you need an interface to fix it. If you have to write raw SQL to fix customer issues, you will hate your life.\n\n## Strategic Guidance\n\n### Hackathon Mode\nSkip it. You are the only admin and you can just use the Supabase/Firebase dashboard to manually edit rows if needed.\n\n### Personal Project\nSkip it. Just use your database GUI (like DBeaver or TablePlus).\n\n### Production SaaS\nDo not build an admin panel from scratch. \n\nUse a low-code tool like Retool, ForestAdmin, or Appsmith. Connect it directly to your production database. Build simple dashboards to view User details, refund Stripe charges, and ban malicious accounts. This will save you hundreds of hours of customer support time.\n\n### Custom Mode\nAn enterprise admin panel must have strict access controls. \n\nA Level 1 Support Agent should be able to reset a password, but they should NOT be able to view sensitive user data or grant admin rights. Every action taken in the admin panel must be logged in an immutable audit trail for compliance purposes.\n\n## Accountability Check\n- [ ] I have set up an internal admin panel.\n`
  },
  {
    key: 'integrations',
    content: `# External Integrations\n\n🕒 **Estimated Time:** 3-5 Hours\n\n---\n\n## Why this matters\nUsers want your product to talk to the tools they already use. \n\n## Strategic Guidance\n\n### Hackathon Mode\nFake them if they are too hard, or use Zapier to quickly stitch things together for the demo.\n\n### Personal Project\nBuild 1 integration (like a Discord bot or Slack webhook) to learn how OAuth2 works.\n\n### Production SaaS\nStart with native Slack or Discord webhooks for notifications. If you need deep integrations (Salesforce, HubSpot), strongly consider using an embedded integration platform like Paragon or Merge.dev. Building and maintaining 10 different OAuth integrations from scratch will drain all your engineering resources.\n\n### Custom Mode\nEnterprises will demand highly specific, custom integrations with their on-premise legacy systems. \n\nYou must expose a robust, rate-limited, and perfectly documented REST or GraphQL API so the enterprise's internal IT team can build the integration themselves. Provide SDKs in Java, Python, and C# to accelerate their work.\n\n## Accountability Check\n- [ ] I have built necessary integrations.\n`
  },
  {
    key: 'testing',
    content: `# Testing\n\n🕒 **Estimated Time:** Ongoing\n\n---\n\n## Why this matters\nWithout tests, every time you add a new feature, you will be terrified of breaking an old one.\n\n## Strategic Guidance\n\n### Hackathon Mode\nZero tests. Absolutely none. You are writing throwaway code.\n\n### Personal Project\nWrite a few unit tests for your most complex business logic functions just to learn Jest or Vitest. Don't aim for 100% coverage.\n\n### Production SaaS\nDo not aim for 100% unit test coverage; it is a waste of time. \n\nInstead, focus on End-to-End (E2E) testing with Playwright or Cypress. Write 5-10 tests that cover your most critical workflows (Signup, Checkout, Core Feature). If those tests pass, you know the app makes money. Let your users find the minor UI bugs.\n\n### Custom Mode\nEnterprise code requires rigorous testing. \n\nYou must have high Unit Test coverage, comprehensive Integration Tests, and full E2E coverage. Furthermore, you must run automated Security Scans (SAST/DAST) and Dependency Audits on every PR. If the tests fail, the deployment is blocked.\n\n## Accountability Check\n- [ ] I have implemented my core E2E tests.\n`
  },
  {
    key: 'documentation',
    content: `# Documentation\n\n🕒 **Estimated Time:** Ongoing\n\n---\n\n## Why this matters\nCode is read 10x more than it is written. If you don't document your architecture, you (or your future hires) will be hopelessly lost in 6 months.\n\n## Strategic Guidance\n\n### Hackathon Mode\nA single ` + '\\`' + `README.md` + '\\`' + ` explaining how to run ` + '\\`' + `npm install` + '\\`' + ` and ` + '\\`' + `npm run dev` + '\\`' + ` is all you need.\n\n### Personal Project\nWrite a good README so when you look at the repo in 2 years, you remember what it does.\n\n### Production SaaS\nYou must maintain two types of documentation: \n\n1. **Internal:** Architecture decisions (ADRs), onboarding guides for new engineers, and environment variable requirements.\n2. **External:** A beautiful, searchable Help Center for your users (using Mintlify or Docusaurus) so they stop emailing customer support with basic questions.\n\n### Custom Mode\nEnterprise documentation must be exhaustive. \n\nYou must provide comprehensive API documentation (Swagger/OpenAPI), deployment runbooks, disaster recovery procedures, and security compliance whitepapers. The enterprise IT team will review this documentation before they approve the purchase.\n\n## Accountability Check\n- [ ] I have documented my project appropriately.\n`
  }
];

let allSuccess = true;
for (const u of topics) {
  if (!updateTopic(u.key, u.content)) {
    allSuccess = false;
  }
}

if (allSuccess) {
  console.log("Batch 5b Deep Content applied!");
} else {
  console.error("Errors occurred in Batch 5b.");
  process.exit(1);
}
