import { useState } from 'react';
import type { Mode } from './TopNav';
import { taxonomy } from '../data/taxonomy';
import { useDocumentStore } from '../hooks/useDocumentStore';
import { DocumentEditor } from './DocumentEditor';
import { motion } from 'framer-motion';

interface MainCanvasProps {
  activePage: string;
  activeMode: Mode;
  projectId: string;
}

export const MainCanvas = ({ activePage, activeMode, projectId }: MainCanvasProps) => {
  let activeTopicName = activePage;
  for (const cat of taxonomy) {
    const topic = cat.topics.find(t => t.id === activePage);
    if (topic) {
      activeTopicName = topic.name;
      break;
    }
  }

  const { content, setContent, isLoaded } = useDocumentStore(projectId, activePage);
  const [isGenerating, setIsGenerating] = useState(false);

  const getMockupText = () => {
    if (activePage === 'prd') {
      return `# Product Requirements Document (PRD)

The PRD is the absolute ground truth for what is being built. It forces you to define what is **Out-of-Scope** before writing any code, preventing architectural drift and feature creep when working with AI.

## 1. Core Objectives
- Define the exact user personas and their primary workflows.
- Establish strict non-goals (what we are NOT building).
- Set the success criteria for the initial MVP.

## 2. The "Anti-Hallucination" Constraints
When prompting an LLM to build features, you must enforce boundaries. Use the following prompt block to lock the AI into your specific requirements:

\`\`\`markdown
You are an expert Staff Engineer acting as the technical lead for this project.

CRITICAL CONSTRAINTS:
1. Do not invent new database tables unless explicitly requested.
2. Adhere strictly to the tech stack defined in TechSpec.md.
3. If a feature contradicts the Non-Goals in the PRD, refuse to build it.
\`\`\`

## 3. Non-Goals (Out of Scope)
For a **${activeMode}** mode project, the following are strictly out of scope:
${activeMode === 'Hackathon' 
  ? '- Custom authentication flows (Use Supabase OAuth instead).\n- CI/CD pipelines and rigorous E2E testing.'
  : '- Spending too much time on logo design.\n- Over-engineering early.'}
`;
    }

    if (activePage === 'schema') {
      return `# Database Schema

Define your tables beforehand. This stops the AI from hallucinating tables mid-build.

\`\`\`prisma
model User {
  id        String   @id @default(uuid())
  email     String   @unique
  createdAt DateTime @default(now())
}
\`\`\`
`;
    }

    if (activePage === 'techspec') {
      return `# Technical Specification

Hard-codes the exact framework versions so the AI stops suggesting outdated or conflicting React libraries.

- **Framework**: Vite + React 18
- **Styling**: Tailwind CSS v3
- **Icons**: Lucide React
`;
    }

    return `# ${activeTopicName}

This is a mock AI generated document for **${activeTopicName}**.
In a real application, this would stream back from an LLM.

## Key Considerations for ${activeMode} Mode

- Focus on speed and efficiency
- Keep scope tight
- Ship early and iterate

> Generated by Kontxt AI
`;
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    setContent('');
    
    const mockupText = getMockupText();

    let currentIndex = 0;
    const interval = setInterval(() => {
      currentIndex += Math.floor(Math.random() * 5) + 3; // Random chunk size for realism
      if (currentIndex >= mockupText.length) {
        setContent(mockupText);
        setIsGenerating(false);
        clearInterval(interval);
      } else {
        setContent(mockupText.slice(0, currentIndex) + '▌');
      }
    }, 15);
  };

  if (!isLoaded) return null;

  return (
    <motion.main 
      key={activePage} // Triggers animation on page change
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ duration: 0.3 }}
      className="flex-1 ml-64 mr-72 max-w-3xl pt-8 pb-24 px-8 w-full"
    >
      <div className="mb-4 inline-block px-3 py-1 bg-muted rounded-md text-xs font-bold text-muted-foreground uppercase tracking-widest">
        Mode: <span className="text-accent">{activeMode}</span>
      </div>
      
      <DocumentEditor
        topicName={activeTopicName}
        content={content}
        onChange={setContent}
        onGenerate={handleGenerate}
        isGenerating={isGenerating}
      />
    </motion.main>
  );
};
