const fs = require('fs');
const path = require('path');

const dirs = [
  './src/data/content/SaaS/Personal',
  './src/data/content/SaaS/Production',
  './src/data/content/SaaS/Hackathon'
];

let processed = 0;

dirs.forEach(dir => {
  if (!fs.existsSync(dir)) return;
  
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));
  
  files.forEach(f => {
    const p = path.join(dir, f);
    let content = fs.readFileSync(p, 'utf8');
    let originalContent = content;
    
    // Convert > **Warning** to > [!WARNING]
    content = content.replace(/^>\s*\*\*(Warning|WARNING)\*\*\s*(\n>)?/gm, '> [!WARNING]\n>');
    
    // Convert > **Tip** to > [!TIP]
    content = content.replace(/^>\s*\*\*(Tip|TIP)\*\*\s*(\n>)?/gm, '> [!TIP]\n>');
    
    // Convert > **Rule** to > [!IMPORTANT]
    content = content.replace(/^>\s*\*\*(Rule|RULE)\*\*\s*(\n>)?/gm, '> [!IMPORTANT]\n>');
    
    // Convert > **Note** to > [!NOTE]
    content = content.replace(/^>\s*\*\*(Note|NOTE)\*\*\s*(\n>)?/gm, '> [!NOTE]\n>');
    
    // Clean up any double empty blockquote lines `> \n> \n`
    content = content.replace(/(>\s*\n){2,}/g, '>\n');
    
    // Fix `>>` which might have been generated by our previous regex
    content = content.replace(/>>/g, '>');
    
    if (content !== originalContent) {
      fs.writeFileSync(p, content, 'utf8');
      processed++;
    }
  });
});

console.log(`Processed and updated ${processed} files.`);
